[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia-eth = "https://attentive-wider-friday.ethereum-sepolia.quiknode.pro/af444895695e92f93792a65fa85f51068cf1ce73/", arb-sepolia = "https://attentive-wider-friday.arbitrum-sepolia.quiknode.pro/af444895695e92f93792a65fa85f51068cf1ce73" }
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@ccip/contracts=lib/ccip/contracts",
    "@chainlink/local/=lib/chainlink-local/",
]

via_ir = true       
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
